// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ8gMe4GVouVyA-3xfibbDou5HwwMkPYA',
    appId: '1:498224046655:web:a9f60f9fe7e81dc4bc8e8a',
    messagingSenderId: '498224046655',
    projectId: 'absensi-gps-7c907',
    authDomain: 'absensi-gps-7c907.firebaseapp.com',
    storageBucket: 'absensi-gps-7c907.appspot.com',
    measurementId: 'G-HRVTSPS75E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4pnvW8x935iCUZyBBlV6WU-kNmrJr9nU',
    appId: '1:498224046655:android:b2e6fc6f9e361651bc8e8a',
    messagingSenderId: '498224046655',
    projectId: 'absensi-gps-7c907',
    storageBucket: 'absensi-gps-7c907.appspot.com',
  );
}
